name: Android APK Build with Buildozer

on:
  push:
    branches:
      - main  # Change this to your branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 3: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 4: Install Buildozer and dependencies
      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      # Step 5: Set up Android SDK
      - name: Install Android SDK Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
          rm commandlinetools-linux-9477386_latest.zip

      # Step 6: Set environment variables for Android SDK
      - name: Set environment variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/tools/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      # Step 7: Accept Android SDK Licenses
      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      # Step 8: Install Android SDK Build Tools and Platform
      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "sources;android-34"

      # Step 9: Clean Previous Builds (optional)
      - name: Clean previous builds
        run: buildozer android clean

      # Step 10: Build the APK with Buildozer
      - name: Build APK
        run: buildozer android debug
