name: Deploy to Railway

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Use Python 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Log in to Railway
        run: railway login --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Add your Railway token as a GitHub secret

      - name: Deploy to Railway
        run: railway up --detach