name: Build Android APK

on:
  push:
    branches:
      - main  # Adjust to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Use the Python version you need

    - name: Install Buildozer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel
        pip install --upgrade pip
        pip install buildozer

    - name: Install additional packages for Buildozer
      run: |
        sudo apt-get install -y git openjdk-11-jdk
        sudo apt-get install -y python3-dev zip unzip zlib1g-dev
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libfontconfig1

    - name: Install Android SDK and AIDL
      run: |
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip -d $HOME/android-sdk
        yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses
        $HOME/android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "extras;android;m2repository"
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $HOME/.bashrc
        echo "export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Build APK
      run: |
        cd bingo_game  # Adjust this path if your project is located elsewhere
        buildozer android clean
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: BingoApp-debug.apk
        path: bin/*.apk  # Path to the generated APK
