name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Install Python and Pip
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install Buildozer and dependencies
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer

      # Download Android SDK Command-line Tools
      - name: Download Android SDK Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
          rm commandlinetools-linux-9477386_latest.zip

      # Set up Android SDK environment
      - name: Set up environment variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/tools/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        shell: bash

      # Accept Android SDK Licenses
      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      # Install Android SDK and Build Tools
      - name: Install Android SDK and Build Tools
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Build APK with Buildozer
      - name: Build APK
        run: buildozer -v -p android debug
