name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Android SDK Command Line Tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O commandlinetools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          rm commandlinetools.zip
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$PATH
          echo "export ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "export PATH=$PATH" >> $GITHUB_ENV

      - name: Accept all SDK licenses
        run: yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses

      - name: Install Build-Tools and Platform Tools
        run: |
          yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager "build-tools;33.0.3" "platforms;android-31"

      - name: Build APK
        run: |
          cd your_project_directory  # Replace with your actual project directory
          buildozer android debug
