name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O android-sdk.zip
          unzip android-sdk.zip -d android-sdk
          mkdir -p $HOME/android-sdk/cmdline-tools
          mv android-sdk/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$PATH
          export PATH=$ANDROID_HOME/platform-tools:$PATH

      - name: Accept all SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Build-Tools 33.0.3 and platform tools
        run: sdkmanager "build-tools;33.0.3" "platforms;android-31"

      - name: Build APK
        run: |
          buildozer android debug
