name: Build Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache libffi-dev python3-pip python3-setuptools \
            git zip unzip zlib1g-dev python3-dev libncurses5 libtinfo5 libjpeg-dev \
            libsqlite3-dev libssl-dev libgstreamer-plugins-base1.0-0 \
            libavcodec-dev libavformat-dev libswscale-dev
        pip install --upgrade Cython==0.29.36 virtualenv

    - name: Install Buildozer
      run: |
        pip install buildozer
        sudo apt install -y openjdk-11-jdk

    - name: Install Android SDK Command-line Tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools

    - name: Set up Android SDK environment
      run: |
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV
      shell: bash

    - name: Accept Android SDK Licenses
      run: |
        yes | sdkmanager --licenses

    - name: Install Android SDK and Build Tools
      run: |
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;35.0.0"

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: kivy-app-apk
        path: bin/*.apk
