name: Build Kivy APK

on:
  push:
    branches:
      - main  # Trigger the build only when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest version of the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python for Buildozer and Python-for-Android
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify Python version

    # Step 3: Install all necessary dependencies for Buildozer and Python-for-Android
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libffi-dev zlib1g-dev \
                                autoconf automake build-essential \
                                libtool pkg-config zlib1g-dev \
                                python3-pip git wget openjdk-11-jdk
        pip install --upgrade pip
        pip install buildozer python-for-android

    # Step 4: Clean any previous builds (useful if there's an issue with caching or previous builds)
    - name: Clean previous builds
      run: |
        buildozer android clean

    # Step 5: Build the APK file using Buildozer (debug mode)
    - name: Build APK
      run: |
        buildozer android debug
