name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Buildozer, Cython, and Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Download Android SDK Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
          rm commandlinetools-linux-9477386_latest.zip

      - name: Set up Environment Variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/tools/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK Build Tools and Platform
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "aidl" "sources;android-34"

      - name: Clean Previous Builds
        run: buildozer android clean

      - name: Build APK
        run: buildozer -v android debug
