name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional, for building with Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Install Buildozer dependencies in a pre-configured Docker container
      # We use the Kivy Docker image that has Buildozer pre-installed
      - name: Build APK with Buildozer (Docker)
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/home/user/hostcwd \
          -w /home/user/hostcwd \
          kivy/buildozer \
          buildozer android debug

      # Step 4: Upload the generated APK as an artifact for downloading
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: bin/*.apk
