name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Android SDK
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Clear SDK Cache
        run: rm -rf $HOME/android-sdk/.cache

      - name: Uninstall Build Tools
        run: sdkmanager --uninstall "build-tools;35.0.0"

      - name: Install Stable Build Tools
        run: sdkmanager "build-tools;34.0.0"

      - name: Build APK
        run: buildozer -v -p android debug  # Ensure this step is correctly configured
